from tkinter import *
from quiz_brain import QuizBrain
THEME_COLOR = "#375362"

class QuizInterface:

    def __init__(self, quiz_brain: QuizBrain):
        self.quiz = quiz_brain
        self.window = Tk()
        self.window.title("Quizzler")
        self.window.config(
            pady=20,
            padx=20,
            bg=THEME_COLOR
        )

        # Create Score labels
        self.score_label = Label(
            text=f"Score: 0",
            bg=THEME_COLOR,
            fg='#ffffff',
            font=("ariel", 12, "")
        )

        self.score_label.grid(column=1, row=0)

        # Create canvas that where questions will display
        self.canvas = Canvas(
            width=300,
            height=250,
            bg="white"
        )
        self.quiz_question = self.canvas.create_text(
            150,
            125,
            width= 280,
            text="",
            font=('ariel', 20, 'italic')
        )
        self.canvas.grid(column=0, row=1, columnspan=2, pady=50)

        # Create buttons
        true_img = PhotoImage(file="images/true.png")
        self.true_button = Button(image=true_img, highlightthickness=0, command=lambda: self.send_answer("true"))
        self.true_button.grid(column=0, row=2)

        false_img = PhotoImage(file="images/false.png")
        self.false_button = Button(image=false_img, highlightthickness=0, command=lambda: self.send_answer("false"))
        self.false_button.grid(column=1, row=2)

        # Display questions generated by api
        self.get_next_question()

        self.window.mainloop()


    def get_next_question(self):
        self.canvas.config(bg="white")
        if self.quiz.still_has_questions():
            q_text = self.quiz.next_question()
            self.canvas.itemconfig(self.quiz_question, text=q_text)
        else:
            self.canvas.itemconfig(self.quiz_question, text="Game Over hope you had fun")
            self.true_button.config(state="disabled")
            self.false_button.config(state="disabled")

    def send_answer(self, answer):

        # Is the answer correct True/Fase
        is_right = self.quiz.check_answer(answer)

        # Set color and text based on if answer is correct
        color, text = ("green", "Correct!") if is_right else ("red", "Wrong X")

        # Change Canvas color and text
        self.canvas.itemconfig(self.quiz_question, text=text)
        self.canvas.config(bg=color)

        # Update Score
        self.score_label.config(text=f"Score: {self.quiz.score}")
        # After 1 second show next question
        self.window.after(1000, func=self.get_next_question)

